#!/usr/bin/env python3
"""
For every printer folder in this repo, compare filament types present in
reference-old-repo/ against what's already bundled, and classify each gap
by whether we have enough machine-compatibility evidence to safely
generate it. See scripts/_filament_lib.py's module docstring and
CLAUDE.md's "Machine compatibility gating" section for the policy.

Usage:
    python3 scripts/find_missing_filaments.py               # all printers
    python3 scripts/find_missing_filaments.py --printer H2D # one printer

Each gap is labeled ALLOW (direct/family/tier-proof evidence) or SKIP
(needs manual review) -- see _filament_lib.classify_gap for exactly what
each label means. Only ALLOW gaps get generated by
scripts/convert_old_repo_to_printer.py.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _filament_lib import PRINTERS, bundle_labels, find_gaps, is_engineering_capable  # noqa: E402


def report_printer(printer_name: str):
    info = PRINTERS[printer_name]
    existing = bundle_labels(info["dir"])

    print(f"\n=== {printer_name} ({info['compatible']}) ===")
    print(f"  existing bundles: {', '.join(name for _, name, _ in existing) or '(none)'}")
    print(f"  engineering-tier capable (has ABS/ASA/PC/PA already): {is_engineering_capable(info['dir'])}")

    for gap in find_gaps(printer_name):
        print(f"  [{gap['verdict']:45s}] {gap['label']:24s} <- {gap['source']['file']}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--printer", choices=sorted(PRINTERS), help="limit to one printer")
    args = parser.parse_args()

    for name in ([args.printer] if args.printer else sorted(PRINTERS)):
        report_printer(name)


if __name__ == "__main__":
    main()
