#!/usr/bin/env python3
"""
Regenerate the "Full profile inventory" markdown table in REFERENCES.md
from the actual .bbsflmt bundles on disk. Run this after adding/removing
any bundle so the table doesn't drift from reality.

Usage:
    python3 scripts/gen_inventory_table.py            # print the table
    python3 scripts/gen_inventory_table.py --check    # exit 1 if REFERENCES.md is stale
"""
import argparse
import json
import re
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCES_MD = REPO_ROOT / "REFERENCES.md"

FOLDERS = ["A1mini", "A2L", "H2C", "H2D", "H2S", "P2S", "X2D/0.4mm"]

# Bundles generated by scripts/convert_old_repo_to_printer.py, not an
# original TINMORRY export -- flagged with a trailing * in the table.
# Anything not an original bundle already committed before that script
# existed counts as generated; detect via a lightweight tag file? Simplest
# robust signal we have: bundle_id's timestamp suffix was minted by the
# converter at generation time (BUNDLE_ID_PREFIX + "_" + name + "_" + unix
# time close to "now"), whereas original TINMORRY exports' bundle_ids carry
# real historical export timestamps. Rather than guess from timestamps,
# the converter scripts always print exactly what they generated -- so
# this script instead trusts an explicit allowlist maintained alongside
# CONVERSIONS-style tooling: any bundle whose filament_settings_id-derived
# name doesn't appear in KNOWN_ORIGINAL_BUNDLES is treated as generated.
KNOWN_ORIGINAL_BUNDLES = {
    ("A1mini", "TINMORRY PETG Matte"), ("A1mini", "TINMORRY TPU 95A"),
    ("A2L", "TINMORRY PETG ECO"), ("A2L", "TINMORRY PETG Metallic"),
    ("A2L", "TINMORRY PLA Rapid"), ("A2L", "TINMORRY PLA Silk"), ("A2L", "TINMORRY TPU 95A"),
    ("H2C", "TINMORRY PLA CF"), ("H2C", "TINMORRY PLA Rapid"),
    ("H2D", "TINMORRY ABS pro"), ("H2D", "TINMORRY ASA CF"), ("H2D", "TINMORRY PLA Matte，"),
    ("H2S", "TINMORRY ASA CF"), ("H2S", "TINMORRY PETG CF"),
    ("H2S", "TINMORRY PLA Rapid"), ("H2S", "TINMORRY TPU 95A"),
    ("P2S", "TINMORRY ABS Pro"), ("P2S", "TINMORRY PP-CF `"), ("P2S", "TINMORRY TPU 95A"),
    ("X2D/0.4mm", "TINMORRY ABS Pro"), ("X2D/0.4mm", "TINMORRY ASA basic"),
    ("X2D/0.4mm", "TINMORRY PETG CF"), ("X2D/0.4mm", "TINMORRY PETG ECO"),
    ("X2D/0.4mm", "TINMORRY PETG GF"), ("X2D/0.4mm", "TINMORRY PETG Galaxy"),
    ("X2D/0.4mm", "TINMORRY PETG Marble"), ("X2D/0.4mm", "TINMORRY PETG Metallic"),
    ("X2D/0.4mm", "TINMORRY PETG Sparkly"), ("X2D/0.4mm", "TINMORRY PLA matte"),
    ("X2D/0.4mm", "TINMORRY TPU 95A"),
}


def bundle_row(folder: str, path: Path):
    with zipfile.ZipFile(path) as z:
        bs = json.loads(z.read("bundle_structure.json"))
        printers = []
        types = set()
        for name in z.namelist():
            if not name.endswith(".json") or name == "bundle_structure.json":
                continue
            profile = json.loads(z.read(name))
            printers.extend(profile.get("compatible_printers", []))
            types.update(profile.get("filament_type", []))
    generated = (folder, bs["filament_name"]) not in KNOWN_ORIGINAL_BUNDLES
    mark = "*" if generated else ""
    return {
        "folder": folder,
        "file": path.name + mark,
        "filament": bs["filament_name"],
        "type": "/".join(sorted(types)),
        "printers": " + ".join(printers),
        "version": bs["version"],
        "bundle_id": bs["bundle_id"] if not generated else re.sub(r"_\d+$", "_&lt;generated&gt;", bs["bundle_id"]),
    }


def build_table():
    rows = []
    for folder in FOLDERS:
        d = REPO_ROOT / folder
        for path in sorted(d.glob("*.bbsflmt")):
            rows.append(bundle_row(folder, path))
    # Known non-bundle entries kept for reference, appended manually.
    rows.append({
        "folder": "P2S", "file": "P2S-PETG-Matte.zip", "filament": "TINMORRY PETG Matte",
        "type": "PETG", "printers": "(nested `.bbsflmt`, not a bundle itself)",
        "version": "—", "bundle_id": "—",
    })
    rows.sort(key=lambda r: (r["folder"], r["file"]))

    lines = ["| Folder | File | Filament | Type | Compatible printer | Studio version | Bundle id |",
             "|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['folder']} | {r['file']} | {r['filament']} | {r['type']} | "
                      f"{r['printers']} | {r['version']} | {r['bundle_id']} |")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if REFERENCES.md's table is stale")
    args = parser.parse_args()

    table = build_table()
    if args.check:
        content = REFERENCES_MD.read_text()
        if table not in content:
            print("REFERENCES.md inventory table is stale -- run without --check and paste it in.", file=sys.stderr)
            sys.exit(1)
        print("REFERENCES.md inventory table is up to date.")
    else:
        print(table)


if __name__ == "__main__":
    main()
